name: CI
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402

    - name: Install dependencies
      run: dotnet restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
   
    - name: Publish Release Version
      run: dotnet publish -c Release 
    
    - name: Deploy to Dubbing Backend server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: /dubbing_backend/Web/bin/Release/
        REMOTE_HOST: 3.121.195.219
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/home/${{ secrets.REMOTE_USER }}/builded_dubbing_app/"
